ALTER TABLE "certification_activity_groups" ADD CONSTRAINT "certification_activity_groups_certification_id_Certification_id_fk" FOREIGN KEY ("certification_id") REFERENCES "public"."Certification"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certification_activity_groups" ADD CONSTRAINT "certification_activity_groups_activity_group_id_ActivityGroup_id_fk" FOREIGN KEY ("activity_group_id") REFERENCES "public"."ActivityGroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certification_certification_modules" ADD CONSTRAINT "certification_certification_modules_certification_id_Certification_id_fk" FOREIGN KEY ("certification_id") REFERENCES "public"."Certification"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certification_certification_modules" ADD CONSTRAINT "certification_certification_modules_certification_module_id_CertificationModule_id_fk" FOREIGN KEY ("certification_module_id") REFERENCES "public"."CertificationModule"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certification_module_activity_groups" ADD CONSTRAINT "certification_module_activity_groups_certification_module_id_CertificationModule_id_fk" FOREIGN KEY ("certification_module_id") REFERENCES "public"."CertificationModule"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "certification_module_activity_groups" ADD CONSTRAINT "certification_module_activity_groups_activity_group_id_ActivityGroup_id_fk" FOREIGN KEY ("activity_group_id") REFERENCES "public"."ActivityGroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_activity_groups" ADD CONSTRAINT "coach_market_place_activity_groups_coach_market_place_id_CoachMarketPlace_id_fk" FOREIGN KEY ("coach_market_place_id") REFERENCES "public"."CoachMarketPlace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_activity_groups" ADD CONSTRAINT "coach_market_place_activity_groups_activity_group_id_ActivityGroup_id_fk" FOREIGN KEY ("activity_group_id") REFERENCES "public"."ActivityGroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_certifications" ADD CONSTRAINT "coach_market_place_certifications_coach_market_place_id_CoachMarketPlace_id_fk" FOREIGN KEY ("coach_market_place_id") REFERENCES "public"."CoachMarketPlace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_certifications" ADD CONSTRAINT "coach_market_place_certifications_certification_id_Certification_id_fk" FOREIGN KEY ("certification_id") REFERENCES "public"."Certification"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_sites" ADD CONSTRAINT "coach_market_place_sites_coach_market_place_id_CoachMarketPlace_id_fk" FOREIGN KEY ("coach_market_place_id") REFERENCES "public"."CoachMarketPlace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_market_place_sites" ADD CONSTRAINT "coach_market_place_sites_site_id_Site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."Site"("id") ON DELETE no action ON UPDATE no action;